# Generated by Django 4.1.7 on 2023-03-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=60)),
                ('Lastname', models.CharField(max_length=60)),
                ('Email', models.EmailField(max_length=60)),
                ('Contact', models.CharField(max_length=60)),
            ],
        ),
    ]
